pickups = ["Hey there baby, wanna suck on my toes?",
           "Whats new pussycat?",
           "Are you from tennessee because youre the only ten I see",
           "Nut",
           "Do you like tennis because you can play with my balls",
           "Hey gorl, youre hot",
           "You a hoe. I like hoes",
           "Are you sure you’re not a parking ticket? Because you’ve got fine written all over you",
           "I’m going to have to ask you to leave. You’re making the other girls look bad.",
           "Call me shrek because i’m head ogre heels for you!",
           "Do you have an inhaler? Because you took my breath away!",
           "If you were a flower you’d be a damnnndelion",
           "Are you a tower? Because eiffel for you!",
           "Are you a bank loan? Because you got my interest",
           "Are you the square root of -1 because you can’t be real"]